export const tabOptions = [
  {
    id: 1,
    tabName: "Buy",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612140buy.svg",
    subtTabOptions: [
      "Flat/Apartment",
      "Builder Floor",
      "Independent House",
      "Independent Villa",
      "Pent House",
      "Residential Land",
      "Farm House",
      "Service apartment",
      "1RK/Studio Apartment",
      "Villament",
      "Others",
    ],
    subtTabOptions2: [
      "Budget",
      "Bedroom",
      "Construction Status",
      "Posted By",
      "Area",
    ],
  },
  {
    id: 2,
    tabName: "Rent",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612180rent.svg",
    subtTabOptions: [
      "Apartment",
      "Independent House",
      "Villa",
      "Residential Land",
      "Farm House",
      "Service apartment",
      "1RK/Studio Apartment",
      "Villament",
      "Others",
    ],
    subtTabOptions2: [
      "Budget",
      "Bedroom",
      "Construction Status",
      "Posted By",
      "Area",
    ],
  },
  {
    id: 3,
    tabName: "PG/CoLiving",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612212pg-coliving.svg",
    subtTabOptions: [
      "Independent Floor",
      "Independent House/Villa",
      "Pent House",
      "Residential Land",
      "Farm House",
      "Service apartment",
      "1RK/Studio Apartment",
      "Flat/Apartment",
    ],
    subtTabOptions2: [
      "Budget",
      "Bedroom",
      "Construction Status",
      "Posted By",
      "Area",
    ],
  },
  {
    id: 4,
    tabName: "CoWorking",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612195coworking.svg",
    subtTabOptions: ["Hor Desk", "Meeting Room", "Dedicated Desk"],
    subtTabOptions2: [
      "Bedroom",
      "Budget",
      "Construction Status",
      "Posted By",
      "Area",
    ],
  },
  {
    id: 5,
    tabName: "Plots/Lands",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612259plots-lands.svg",
    subtTabOptions: [
      "Residential Land",
      "Farm House",
      "Service apartment",
      "1RK/Studio Apartment",
      "Villament",
      "Others",
    ],
    subtTabOptions2: [
      "Bedroom",
      "Budget",
      "Construction Status",
      "Posted By",
      "Area",
    ],
  },
  {
    id: 6,
    tabName: "Projects",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612276projects.svg",
    subtTabOptions: [
      "Apartment",
      "Pent House",
      "Plot",
      "Row House",
      "Studio",
      "Villament",
      "Villa",
    ],
    subtTabOptions2: [
      "Bedroom",
      "Budget",
      "Construction Status",
      "Posted By",
      "Area",
    ],
  },
];
